name: Daily Run

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "pnpm"
      - run: make install
      - run: echo "${{ secrets.SERVICE_ACCOUNT_KEY_BASE64_TEXT }}" | base64 --decode > ServiceAccountKey.json
      - run: echo "${{ secrets.WEBSITES_CONFIG_BASE64 }}" | base64 --decode > config/websites.yaml
      - run: make run
        env:
          GA_KEYFILE: ServiceAccountKey.json
          CONFIG_FILE_PATH: config/websites.yaml
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Notify failure
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Daily run failed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
            "$SLACK_WEBHOOK"
